export const ESTADOS_GENERICOS = ["ACTIVO", "INACTIVO"];

export const schema = {
  facultad: {
    resource: "Facultad",
    idField: "idFacultad",
    label: "Facultad",
    labelPlural: "Facultades",
    displayField: "nombreFacultad",
    fields: [
      { name: "codigoFacultad", label: "Código", type: "text", required: true },
      { name: "nombreFacultad", label: "Nombre", type: "text", required: true },
      { name: "estadoFacultad", label: "Estado", type: "select", options: ESTADOS_GENERICOS, required: true },
    ],
  },
  carrera: {
    resource: "Carrera",
    idField: "idCarrera",
    label: "Carrera",
    labelPlural: "Carreras",
    displayField: "nombreCarrera",
    fields: [
      { name: "codigoCarrera", label: "Código", type: "text", required: true },
      { name: "nombreCarrera", label: "Nombre", type: "text", required: true },
      { name: "totalCiclos", label: "Total de ciclos", type: "number", required: true },
      { name: "estadoCarrera", label: "Estado", type: "select", options: ESTADOS_GENERICOS, required: true },
      { name: "idFacultad", label: "Facultad", type: "select", fk: "facultad", required: true },
    ],
  },
  pensum: {
    resource: "Pensum",
    idField: "idPensum",
    label: "Pensum",
    labelPlural: "Pensums",
    displayField: "codigoPensum",
    fields: [
      { name: "codigoPensum", label: "Código", type: "text", required: true },
      { name: "anioPensum", label: "Año", type: "number", required: true },
      { name: "jornadaPensum", label: "Jornada", type: "text", required: true },
      { name: "estadoPensum", label: "Estado", type: "select", options: ESTADOS_GENERICOS, required: true },
      { name: "idCarrera", label: "Carrera", type: "select", fk: "carrera", required: true },
    ],
  },
  curso: {
    resource: "Curso",
    idField: "idCurso",
    label: "Curso",
    labelPlural: "Cursos",
    displayField: "nombreCurso",
    fields: [
      { name: "codigoCurso", label: "Código", type: "text", required: true },
      { name: "nombreCurso", label: "Nombre", type: "text", required: true },
      { name: "creditosCurso", label: "Créditos", type: "number", required: true },
      { name: "requiereLaboratorio", label: "Requiere laboratorio", type: "boolean" },
      { name: "estadoCurso", label: "Estado", type: "select", options: ESTADOS_GENERICOS, required: true },
    ],
  },
  pensumCurso: {
    resource: "PensumCurso",
    idField: "idPensumCurso",
    label: "Curso de pensum",
    labelPlural: "Cursos de pensum",
    displayField: null,
    fields: [
      { name: "idPensum", label: "Pensum", type: "select", fk: "pensum", required: true },
      { name: "idCurso", label: "Curso", type: "select", fk: "curso", required: true },
      { name: "ciclo", label: "Ciclo", type: "number", required: true },
      { name: "esObligatorio", label: "Obligatorio", type: "boolean" },
    ],
  },
  requisitoCurso: {
    resource: "RequisitoCurso",
    idField: "idRequisitoCurso",
    label: "Requisito de curso",
    labelPlural: "Requisitos de curso",
    displayField: "descripcionRequisito",
    fields: [
      { name: "idPensumCurso", label: "Curso de pensum", type: "select", fk: "pensumCurso", required: true },
      { name: "tipoRequisito", label: "Tipo de requisito", type: "text", required: true },
      { name: "idCursoRequerido", label: "Curso requerido", type: "select", fk: "curso", required: true },
      { name: "creditosMinimos", label: "Créditos mínimos", type: "number", required: true },
      { name: "descripcionRequisito", label: "Descripción", type: "text", required: true },
    ],
  },
  rol: {
    resource: "Rol",
    idField: "idRol",
    label: "Rol",
    labelPlural: "Roles",
    displayField: "nombreRol",
    fields: [
      { name: "nombreRol", label: "Nombre", type: "text", required: true },
      { name: "descripcionRol", label: "Descripción", type: "text", required: true },
      { name: "estadoRol", label: "Estado", type: "select", options: ESTADOS_GENERICOS, required: true },
    ],
  },
  permiso: {
    resource: "Permiso",
    idField: "idPermiso",
    label: "Permiso",
    labelPlural: "Permisos",
    displayField: "nombrePermiso",
    fields: [
      { name: "nombrePermiso", label: "Nombre", type: "text", required: true },
      { name: "descripcionPermiso", label: "Descripción", type: "text", required: true },
    ],
  },
  rolPermiso: {
    resource: "RolPermiso",
    idField: null,
    compositeKey: ["idRol", "idPermiso"],
    label: "Permiso de rol",
    labelPlural: "Permisos por rol",
    displayField: null,
    fields: [
      { name: "idRol", label: "Rol", type: "select", fk: "rol", required: true },
      { name: "idPermiso", label: "Permiso", type: "select", fk: "permiso", required: true },
    ],
  },
  usuario: {
    resource: "Usuario",
    idField: "idUsuario",
    label: "Usuario",
    labelPlural: "Usuarios",
    displayField: "nombreUsuario",
    fields: [
      { name: "nombreUsuario", label: "Nombre de usuario", type: "text", required: true },
      { name: "correoLoginUsuario", label: "Correo de acceso", type: "text", required: true },
      { name: "correoRecuperacionUsuario", label: "Correo de recuperación", type: "text", required: true },
      { name: "contrasenaHash", label: "Contraseña", type: "text", required: true },
      { name: "tienePassTemporal", label: "Contraseña temporal", type: "boolean" },
      { name: "estadoUsuario", label: "Estado", type: "select", options: ESTADOS_GENERICOS, required: true },
      { name: "fechaRegistroUsuario", label: "Fecha de registro", type: "date", required: true },
      { name: "idRol", label: "Rol", type: "select", fk: "rol", required: true },
    ],
  },
  catedratico: {
    resource: "Catedratico",
    idField: "idCatedratico",
    label: "Catedrático",
    labelPlural: "Catedráticos",
    displayField: "nombresCatedratico",
    fields: [
      { name: "codigoCatedratico", label: "Código", type: "number", required: true },
      { name: "dpiCatedratico", label: "DPI", type: "text", required: true },
      { name: "nombresCatedratico", label: "Nombres", type: "text", required: true },
      { name: "apellidosCatedratico", label: "Apellidos", type: "text", required: true },
      { name: "telefonoCatedratico", label: "Teléfono", type: "text", required: true },
      { name: "profesionCatedratico", label: "Profesión", type: "text", required: true },
      { name: "estadoCatedratico", label: "Estado", type: "select", options: ESTADOS_GENERICOS, required: true },
      { name: "idUsuario", label: "Usuario", type: "select", fk: "usuario", required: true },
    ],
  },
  estudiante: {
    resource: "Estudiante",
    idField: "idEstudiante",
    label: "Estudiante",
    labelPlural: "Estudiantes",
    displayField: "nombresEstudiante",
    fields: [
      { name: "nombresEstudiante", label: "Nombres", type: "text", required: true },
      { name: "apellidosEstudiante", label: "Apellidos", type: "text", required: true },
      { name: "carnetEstudiante", label: "Carné", type: "text", required: true },
      { name: "dpiEstudiante", label: "DPI", type: "text", required: true },
      { name: "fechaNacimientoEstudiante", label: "Fecha de nacimiento", type: "date", required: true },
      { name: "direccionEstudiante", label: "Dirección", type: "text", required: true },
      { name: "telefonoEstudiante", label: "Teléfono", type: "text", required: true },
      { name: "cicloEstudiante", label: "Ciclo actual", type: "number", required: true },
      { name: "estadoEstudiante", label: "Estado", type: "select", options: ESTADOS_GENERICOS, required: true },
      { name: "idUsuario", label: "Usuario", type: "select", fk: "usuario", required: true },
      { name: "idPensum", label: "Pensum", type: "select", fk: "pensum", required: true },
    ],
  },
  edificio: {
    resource: "Edificio",
    idField: "idEdificio",
    label: "Edificio",
    labelPlural: "Edificios",
    displayField: "nombreEdificio",
    fields: [
      { name: "nombreEdificio", label: "Nombre", type: "text", required: true },
      { name: "codigoEdificio", label: "Código", type: "text", required: true },
      { name: "sedeEdificio", label: "Sede", type: "text", required: true },
      { name: "ubicacionEdificio", label: "Ubicación", type: "text", required: true },
      { name: "estadoEdificio", label: "Estado", type: "select", options: ESTADOS_GENERICOS, required: true },
    ],
  },
  salon: {
    resource: "Salon",
    idField: "idSalon",
    label: "Salón",
    labelPlural: "Salones",
    displayField: "nombreSalon",
    fields: [
      { name: "nombreSalon", label: "Nombre", type: "text", required: true },
      { name: "codigoSalon", label: "Código", type: "text", required: true },
      { name: "estadoSalon", label: "Estado", type: "select", options: ESTADOS_GENERICOS, required: true },
      { name: "capacidadSalon", label: "Capacidad", type: "number", required: true },
      { name: "tipoEspacio", label: "Tipo de espacio", type: "text", required: true },
      { name: "nivelSalon", label: "Nivel", type: "number", required: true },
      { name: "idEdificio", label: "Edificio", type: "select", fk: "edificio", required: true },
    ],
  },
  laboratorio: {
    resource: "Laboratorio",
    idField: "idLaboratorio",
    label: "Laboratorio",
    labelPlural: "Laboratorios",
    displayField: "nombreLaboratorio",
    fields: [
      { name: "nombreLaboratorio", label: "Nombre", type: "text", required: true },
      { name: "descripcionLaboratorio", label: "Descripción", type: "text" },
      { name: "estadoLaboratorio", label: "Estado", type: "select", options: ESTADOS_GENERICOS, required: true },
      { name: "idSalon", label: "Salón", type: "select", fk: "salon", required: true },
    ],
  },
  periodoAcademico: {
    resource: "PeriodoAcademico",
    idField: "idPeriodo",
    label: "Período académico",
    labelPlural: "Períodos académicos",
    displayField: "codigoPeriodo",
    fields: [
      { name: "codigoPeriodo", label: "Código", type: "text", required: true },
      { name: "descripcionPeriodo", label: "Descripción", type: "text", required: true },
      { name: "tipoPeriodo", label: "Tipo", type: "text", required: true },
      { name: "fechaInicio", label: "Fecha de inicio", type: "date", required: true },
      { name: "fechaFin", label: "Fecha de fin", type: "date", required: true },
      { name: "permiteInscripcion", label: "Permite inscripción", type: "boolean" },
      { name: "permiteAsignacion", label: "Permite asignación", type: "boolean" },
      { name: "estadoPeriodo", label: "Estado", type: "select", options: ESTADOS_GENERICOS, required: true },
    ],
  },
  seccion: {
    resource: "Seccion",
    idField: "idSeccion",
    label: "Sección",
    labelPlural: "Secciones",
    displayField: "codigoSeccion",
    fields: [
      { name: "codigoSeccion", label: "Código", type: "text", required: true },
      { name: "jornada", label: "Jornada", type: "text", required: true },
      { name: "cupoMaximo", label: "Cupo máximo", type: "number", required: true },
      { name: "estadoSeccion", label: "Estado", type: "select", options: ESTADOS_GENERICOS, required: true },
      { name: "idCurso", label: "Curso", type: "select", fk: "curso", required: true },
      { name: "idPeriodo", label: "Período académico", type: "select", fk: "periodoAcademico", required: true },
      { name: "idCatedratico", label: "Catedrático", type: "select", fk: "catedratico", required: true },
      { name: "idSalon", label: "Salón", type: "select", fk: "salon", required: true },
    ],
  },
  horarioSeccion: {
    resource: "HorarioSeccion",
    idField: "idHorario",
    label: "Horario de sección",
    labelPlural: "Horarios de sección",
    displayField: null,
    fields: [
      { name: "diaSemana", label: "Día de la semana", type: "text", required: true },
      { name: "horaInicio", label: "Hora de inicio", type: "time", required: true },
      { name: "horaFin", label: "Hora de fin", type: "time", required: true },
      { name: "tipoSesion", label: "Tipo de sesión", type: "text", required: true },
      { name: "idSeccion", label: "Sección", type: "select", fk: "seccion", required: true },
    ],
  },
  seccionLaboratorio: {
    resource: "SeccionLaboratorio",
    idField: "idSeccionLaboratorio",
    label: "Sección de laboratorio",
    labelPlural: "Secciones de laboratorio",
    displayField: null,
    fields: [
      { name: "diaSemana", label: "Día de la semana", type: "text", required: true },
      { name: "costoExtra", label: "Costo extra", type: "decimal", required: true },
      { name: "idSeccion", label: "Sección", type: "select", fk: "seccion", required: true },
      { name: "idLaboratorio", label: "Laboratorio", type: "select", fk: "laboratorio", required: true },
    ],
  },
  inscripcion: {
    resource: "Inscripcion",
    idField: "idInscripcion",
    label: "Inscripción",
    labelPlural: "Inscripciones",
    displayField: null,
    fields: [
      { name: "fechaInscripcion", label: "Fecha de inscripción", type: "date", required: true },
      { name: "costoInscripcion", label: "Costo de inscripción", type: "decimal" },
      { name: "estadoInscripcion", label: "Estado", type: "select", options: ESTADOS_GENERICOS, required: true },
      { name: "montoMensual", label: "Monto mensual", type: "decimal", required: true },
      { name: "cicloInscrito", label: "Ciclo inscrito", type: "number", required: true },
      { name: "estadoSolvencia", label: "Estado de solvencia", type: "text", required: true },
      { name: "idEstudiante", label: "Estudiante", type: "select", fk: "estudiante", required: true },
      { name: "idPeriodoAcademico", label: "Período académico", type: "select", fk: "periodoAcademico", required: true },
    ],
  },
  asignacion: {
    resource: "Asignacion",
    idField: "idAsignacion",
    label: "Asignación",
    labelPlural: "Asignaciones",
    displayField: null,
    fields: [
      { name: "fechaAsignacion", label: "Fecha de asignación", type: "date", required: true },
      { name: "subTotalLaboratorios", label: "Subtotal de laboratorios", type: "decimal" },
      { name: "totalPago", label: "Total a pagar", type: "decimal", required: true },
      { name: "estadoAsignacion", label: "Estado", type: "select", options: ESTADOS_GENERICOS, required: true },
      { name: "idInscripcion", label: "Inscripción", type: "select", fk: "inscripcion", required: true },
    ],
  },
  detalleAsignacion: {
    resource: "DetalleAsignacion",
    idField: "idDetalleAsignacion",
    label: "Detalle de asignación",
    labelPlural: "Detalles de asignación",
    displayField: null,
    fields: [
      { name: "estadoDetalle", label: "Estado", type: "select", options: ESTADOS_GENERICOS, required: true },
      { name: "costoLaboratorio", label: "Costo de laboratorio", type: "decimal" },
      { name: "notaFinal", label: "Nota final", type: "decimal", required: true },
      { name: "resultado", label: "Resultado", type: "text", required: true },
      { name: "fechaResultado", label: "Fecha de resultado", type: "date", required: true },
      { name: "idAsignacion", label: "Asignación", type: "select", fk: "asignacion", required: true },
      { name: "idSeccion", label: "Sección", type: "select", fk: "seccion", required: true },
    ],
  },
};

export const navGroups = [
  {
    title: "Núcleo académico",
    items: ["facultad", "carrera", "pensum", "curso", "pensumCurso", "requisitoCurso"],
  },
  {
    title: "Personas y accesos",
    items: ["rol", "permiso", "rolPermiso", "usuario", "catedratico", "estudiante"],
  },
  {
    title: "Infraestructura",
    items: ["edificio", "salon", "laboratorio"],
  },
  {
    title: "Operación académica",
    items: [
      "periodoAcademico",
      "seccion",
      "horarioSeccion",
      "seccionLaboratorio",
      "inscripcion",
      "asignacion",
      "detalleAsignacion",
    ],
  },
];
